title:              旅遊指南
email:              your-email@example.com
description:        Travel Guide
author:             LawrenceCHH
baseurl:            "/travel"
url:                "https://lawrencechh.github.io"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics (blank = disabled, no external request)
google_analytics:

# Build settings
markdown:           kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
